=== AdrianGarciaB/ExerciciJavaFX/src/main/resources/xml/cinemes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="dataroot" type="datarootType"/>
  <xs:complexType name="CINEMESType">
    <xs:sequence>
      <xs:element type="xs:string" name="CINEID"/>
      <xs:element type="xs:string" name="CINENOM"/>
      <xs:element type="xs:string" name="CINEADRECA"/>
      <xs:element type="xs:string" name="LOCALITAT"/>
      <xs:element type="xs:string" name="COMARCA"/>
      <xs:element name="PROVINCIA">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="BARCELONA"/>
            <xs:enumeration value="GIRONA"/>
            <xs:enumeration value="LLEIDA"/>
            <xs:enumeration value="TARRAGONA"/>
            <xs:enumeration value="ANDORRA"/>
            <xs:enumeration value="ILLES BALEARS"/>
            <xs:enumeration value="--"/>
            <xs:enumeration value="VALÈNCIA"/>
            <xs:enumeration value="FRANÇA"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="datarootType">
    <xs:sequence>
      <xs:element type="CINEMESType" name="CINEMES" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="generated"/>
  </xs:complexType>
</xs:schema>

=== AdrianGarciaB/ExerciciJavaFX/src/main/resources/xml/cinemes.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cinemes.xsd" generated="2020-02-21T17:44:56">
<CINEMES>
<CINEID>37147</CINEID>
<CINENOM>Cinemes Girona</CINENOM>
<CINEADRECA>C. de Girona, 173, 08025 Barcelona</CINEADRECA>
<LOCALITAT>Barcelona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37153</CINEID>
<CINENOM>Filmoteca de Catalunya</CINENOM>
<CINEADRECA>Pl. de Salvador Seguí, 1-9, 08001 Barcelona</CINEADRECA>
<LOCALITAT>Barcelona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37156</CINEID>
<CINENOM>Cines FULL de Cornellà de Llobregat</CINENOM>
<CINEADRECA>Av. Baix Llobregat, s/n, Centre Comercial Splau, 08940 Cornellà de Llobregat</CINEADRECA>
<LOCALITAT>Cornellà de Llobregat</LOCALITAT>
<COMARCA>Baix Llobregat</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37157</CINEID>
<CINENOM>CAT Cines Figueres ACEC</CINENOM>
<CINEADRECA>Ronda Sud, 17, 17600 Figueres, Girona ‎
17600 Figueras</CINEADRECA>
<LOCALITAT>Figueres</LOCALITAT>
<COMARCA>Alt Empordà</COMARCA>
<PROVINCIA>GIRONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37160</CINEID>
<CINENOM>Ocine Girona</CINENOM>
<CINEADRECA>C/ Pont de la Barca, 12, 17007 Girona</CINEADRECA>
<LOCALITAT>Girona</LOCALITAT>
<COMARCA>Gironès</COMARCA>
<PROVINCIA>GIRONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37161</CINEID>
<CINENOM>Ocine Granollers - El Nord</CINENOM>
<CINEADRECA>Centre Comercial El Nord, Carrer del Montseny,4, 08400 Granollers</CINEADRECA>
<LOCALITAT>Granollers</LOCALITAT>
<COMARCA>Vallès Oriental</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37162</CINEID>
<CINENOM>JCA Cinemes Lleida - Alpicat</CINENOM>
<CINEADRECA>JCA Cinemes Alpicat, Partida Pla de Monsó 25110 Alpicat</CINEADRECA>
<LOCALITAT>Alpicat</LOCALITAT>
<COMARCA>Segrià</COMARCA>
<PROVINCIA>LLEIDA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37164</CINEID>
<CINENOM>Cines Bages Centre de Manresa</CINENOM>
<CINEADRECA>Els Trullols, s/n, 08243 Manresa</CINEADRECA>
<LOCALITAT>Manresa</LOCALITAT>
<COMARCA>Bages</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37168</CINEID>
<CINENOM>Cines Olot</CINENOM>
<CINEADRECA>Carrer de Josep Ayats, 10, 17800 Olot</CINEADRECA>
<LOCALITAT>Olot</LOCALITAT>
<COMARCA>Garrotxa</COMARCA>
<PROVINCIA>GIRONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37171</CINEID>
<CINENOM>Cines Imperial de Sabadell</CINENOM>
<CINEADRECA>Pl. Imperial, 4, 08202 Sabadell</CINEADRECA>
<LOCALITAT>Sabadell</LOCALITAT>
<COMARCA>Vallès Occidental</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37172</CINEID>
<CINENOM>Cinemes Sant Cugat</CINENOM>
<CINEADRECA>Avinguda del Pla del Vinyet, 50, 08172 Sant Cugat del Vallès</CINEADRECA>
<LOCALITAT>Sant Cugat del Vallès</LOCALITAT>
<COMARCA>Vallès Occidental</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37174</CINEID>
<CINENOM>Ocine Tarragona - Les Gavarres</CINENOM>
<CINEADRECA>C.C. Les Gavarres, Autovía Tarragona - Reus, Parc.2, 43006 Tarragona‎‎</CINEADRECA>
<LOCALITAT>Tarragona</LOCALITAT>
<COMARCA>Tarragonès</COMARCA>
<PROVINCIA>TARRAGONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37177</CINEID>
<CINENOM>JCA Cinemes Tarragona - Valls</CINENOM>
<CINEADRECA>C. de Sant Antoni Maria Claret, 8, 43800 Valls</CINEADRECA>
<LOCALITAT>Valls</LOCALITAT>
<COMARCA>Alt Camp</COMARCA>
<PROVINCIA>TARRAGONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37178</CINEID>
<CINENOM>Multicines Sucre de Vic</CINENOM>
<CINEADRECA>C. de la Llotja, 9, 08500 Vic</CINEADRECA>
<LOCALITAT>Vic</LOCALITAT>
<COMARCA>Osona</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37179</CINEID>
<CINENOM>Kubrick Cinema de Vilafranca del Penedès</CINENOM>
<CINEADRECA>Carrer del General Prim, 7, 08720 Vilafranca del Penedès</CINEADRECA>
<LOCALITAT>Vilafranca del Penedès</LOCALITAT>
<COMARCA>Alt Penedès</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37182</CINEID>
<CINENOM>Cines Verdi</CINENOM>
<CINEADRECA>C. de Verdi, 32, 08012 Barcelona</CINEADRECA>
<LOCALITAT>Barcelona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37183</CINEID>
<CINENOM>Screenbox Funatic de Lleida</CINENOM>
<CINEADRECA>C. Pi i Margall, 26, 25004 Lleida</CINEADRECA>
<LOCALITAT>Lleida</LOCALITAT>
<COMARCA>Segrià</COMARCA>
<PROVINCIA>LLEIDA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37143</CINEID>
<CINENOM>Ocine Màgic Badalona</CINENOM>
<CINEADRECA>C/ Concòrdia, 1, 08917 Badalona</CINEADRECA>
<LOCALITAT>Badalona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37187</CINEID>
<CINENOM>CineBaix de Sant Feliu de Llobregat</CINENOM>
<CINEADRECA>C. de Joan Batllori, 21, 08980 Sant Feliu de Llobregat</CINEADRECA>
<LOCALITAT>Sant Feliu de Llobregat</LOCALITAT>
<COMARCA>Baix Llobregat</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37189</CINEID>
<CINENOM>Cinema Catalunya de Terrassa</CINENOM>
<CINEADRECA>Carrer de Sant Pere, 9, 08221 Terrassa, Barcelona</CINEADRECA>
<LOCALITAT>Terrassa</LOCALITAT>
<COMARCA>Vallès Occidental</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37192</CINEID>
<CINENOM>Cine Era Audiovisuau de Vielha</CINENOM>
<CINEADRECA>Avenguda Baile Calbeto Barra, s/n 25530 Vielha e Mijaran</CINEADRECA>
<LOCALITAT>Vielha e Mijaran</LOCALITAT>
<COMARCA>Aran</COMARCA>
<PROVINCIA>LLEIDA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37193</CINEID>
<CINENOM>Cinema Casal d'Agramunt</CINENOM>
<CINEADRECA>Carrer Baixada Mercadal, 7 25310 Agramunt, Lleida ‎</CINEADRECA>
<LOCALITAT>Agramunt</LOCALITAT>
<COMARCA>Urgell</COMARCA>
<PROVINCIA>LLEIDA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37194</CINEID>
<CINENOM>Cinema Casal Montblanquí</CINENOM>
<CINEADRECA>C. Casal, 2, 43400 Montblanc</CINEADRECA>
<LOCALITAT>Montblanc</LOCALITAT>
<COMARCA>Conca de Barberà</COMARCA>
<PROVINCIA>TARRAGONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37197</CINEID>
<CINENOM>Teatre Cinema Armengol de Bellpuig</CINENOM>
<CINEADRECA>Plaça Ramon Folch, 17, Bellpuig</CINEADRECA>
<LOCALITAT>Bellpuig</LOCALITAT>
<COMARCA>Urgell</COMARCA>
<PROVINCIA>LLEIDA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37203</CINEID>
<CINENOM>Palau Balaña Multicines</CINENOM>
<CINEADRECA>C. de Sant Antoni, 43, 08014 Barcelona</CINEADRECA>
<LOCALITAT>Barcelona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37208</CINEID>
<CINENOM>Cines Filmax Gran Via 4DX de l'Hospitalet de Llobregat</CINENOM>
<CINEADRECA>C.C. Gran Vía 2, Avda. Gran Vía, 75, 08908 Hospitalet, Barcelona</CINEADRECA>
<LOCALITAT>L’Hospitalet de Llobregat</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37210</CINEID>
<CINENOM>Ocine Platja d’Aro – Parc d’Aro</CINENOM>
<CINEADRECA>Ctra. Platja d'Aro a S'Agaró, Polígon la Bòvila, s/n, 17250 Castell-Platja d’Aro</CINEADRECA>
<LOCALITAT>Castell-Platja d’Aro</LOCALITAT>
<COMARCA>Baix Empordà</COMARCA>
<PROVINCIA>GIRONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37213</CINEID>
<CINENOM>Ocine Roquetes</CINENOM>
<CINEADRECA>Ocine Roquetes, Carrer Severo Ochoa, Roquetes</CINEADRECA>
<LOCALITAT>Roquetes</LOCALITAT>
<COMARCA>Baix Ebre</COMARCA>
<PROVINCIA>TARRAGONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37215</CINEID>
<CINENOM>Cinemes Can Castellet de Sant Boi de Llobregat</CINENOM>
<CINEADRECA>C. Jaume I, 32, 08830 Sant Boi de Llobregat</CINEADRECA>
<LOCALITAT>Sant Boi de Llobregat</LOCALITAT>
<COMARCA>Baix Llobregat</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37216</CINEID>
<CINENOM>Ocine Sant Celoni – Altrium</CINENOM>
<CINEADRECA>Ctra. Olzinelles, s/n, 08470 Sant Celoni</CINEADRECA>
<LOCALITAT>Sant Celoni</LOCALITAT>
<COMARCA>Vallès Oriental</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37217</CINEID>
<CINENOM>Ocine El Vendrell – Les Mates</CINENOM>
<CINEADRECA>Centre Comercial Les Mates, Carrer les Mates, S/N, 43700 El Vendrell</CINEADRECA>
<LOCALITAT>El Vendrell</LOCALITAT>
<COMARCA>Baix Penedès</COMARCA>
<PROVINCIA>TARRAGONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37218</CINEID>
<CINENOM>Ocine Vila-seca – Port Halley</CINENOM>
<CINEADRECA>Avinguda de l'Alcalde Pere Molas, 36, 43480 Vila-seca</CINEADRECA>
<LOCALITAT>Vila-seca</LOCALITAT>
<COMARCA>Tarragonès</COMARCA>
<PROVINCIA>TARRAGONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37219</CINEID>
<CINENOM>Cinemes Illa Carlemany de Les Escaldes</CINENOM>
<CINEADRECA>Av. Carlemany, 70, AD700 Escaldes-Engordany</CINEADRECA>
<LOCALITAT>Escaldes-Engordany</LOCALITAT>
<COMARCA>Escaldes-Engordany</COMARCA>
<PROVINCIA>ANDORRA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37221</CINEID>
<CINENOM>Cinema Els Til·lers de Sort</CINENOM>
<CINEADRECA>Pg. dels Til·lers, s/n, 25560 Sort</CINEADRECA>
<LOCALITAT>Sort</LOCALITAT>
<COMARCA>Pallars Sobirà</COMARCA>
<PROVINCIA>LLEIDA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37222</CINEID>
<CINENOM>Auditori de la Biblioteca Municipal Mestre Martí Tauler de Rubí</CINENOM>
<CINEADRECA>Carrer d'Aribau, 5, 08191 Rubí</CINEADRECA>
<LOCALITAT>Rubí</LOCALITAT>
<COMARCA>Vallès Occidental</COMARCA>
<PROVINCIA>BARCELONA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37225</CINEID>
<CINENOM>Cinemes Majèstic de Tàrrega</CINENOM>
<CINEADRECA>Avinguda de Catalunya, 56, 25300 Tàrrega, Lleida</CINEADRECA>
<LOCALITAT>Tàrrega</LOCALITAT>
<COMARCA>Urgell</COMARCA>
<PROVINCIA>LLEIDA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37228</CINEID>
<CINENOM>Cinemes Guiu de La Seu d'Urgell</CINENOM>
<CINEADRECA>Avinguda del Salòria, 55, 25700 Seu D'Urgell (la), Lleida</CINEADRECA>
<LOCALITAT>La Seu d'Urgell</LOCALITAT>
<COMARCA>Alt Urgell</COMARCA>
<PROVINCIA>LLEIDA</PROVINCIA>
</CINEMES>
<CINEMES>
<CINEID>37229</CINEID>
