=== AdrianGarciaB/ExerciciJavaFX/src/main/resources/xml/film_sessions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="dataroot" type="datarootType"/>
  <xs:complexType name="SESSIONSType">
    <xs:sequence>
      <xs:element type="xs:string" name="IDFILM"/>
      <xs:element type="xs:string" name="ses_id"/>
      <xs:element type="xs:string" name="CINEID"/>
      <xs:element type="xs:string" name="TITOL"/>
      <xs:element type="xs:string" name="ses_data"/>
      <xs:element type="xs:string" name="CINENOM"/>
      <xs:element type="xs:string" name="LOCALITAT"/>
      <xs:element type="xs:string" name="COMARCA"/>
      <xs:element name="CICLEID">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="57257"/>
            <xs:enumeration value="57142"/>
            <xs:enumeration value="57261"/>
            <xs:enumeration value="57141"/>
            <xs:enumeration value="57222"/>
            <xs:enumeration value="57253"/>
            <xs:enumeration value="57221"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ver">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="VD"/>
            <xs:enumeration value="VO"/>
            <xs:enumeration value="VOSC"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="preu"/>
      <xs:element type="xs:string" name="ORDRESESSIO"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="datarootType">
    <xs:sequence>
      <xs:element type="SESSIONSType" name="SESSIONS" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="generated"/>
  </xs:complexType>
</xs:schema>

=== AdrianGarciaB/ExerciciJavaFX/src/main/resources/xml/film_sessions.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="film_sessions.xsd" generated="2020-02-21T17:45:40">
<SESSIONS>
<IDFILM>33325</IDFILM>
<ses_id>1</ses_id>
<CINEID>37177</CINEID>
<TITOL>Zibila i el poder de les ratlles</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>JCA Cinemes Tarragona - Valls</CINENOM>
<LOCALITAT>Valls</LOCALITAT>
<COMARCA>Alt Camp</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33282</IDFILM>
<ses_id>1</ses_id>
<CINEID>37171</CINEID>
<TITOL>Sense sostre</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Cines Imperial de Sabadell</CINENOM>
<LOCALITAT>Sabadell</LOCALITAT>
<COMARCA>Vallès Occidental</COMARCA>
<CICLEID>1</CICLEID>
<ver>VO</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33262</IDFILM>
<ses_id>1</ses_id>
<CINEID>37203</CINEID>
<TITOL>Operació Panda</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Palau Balaña Multicines</CINENOM>
<LOCALITAT>Barcelona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33262</IDFILM>
<ses_id>1</ses_id>
<CINEID>37160</CINEID>
<TITOL>Operació Panda</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Ocine Girona</CINENOM>
<LOCALITAT>Girona</LOCALITAT>
<COMARCA>Gironès</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33380</IDFILM>
<ses_id>1</ses_id>
<CINEID>37153</CINEID>
<TITOL>El viatge de Mastorna de Federico Fellini. Un experiment de reconstrucció</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Filmoteca de Catalunya</CINENOM>
<LOCALITAT>Barcelona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<CICLEID>1</CICLEID>
<ver>VOSC</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33372</IDFILM>
<ses_id>1</ses_id>
<CINEID>37406</CINEID>
<TITOL>Les bones intencions</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Cinemes Texas</CINENOM>
<LOCALITAT>Barcelona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<CICLEID>1</CICLEID>
<ver>VOSC</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>32199</IDFILM>
<ses_id>1</ses_id>
<CINEID>37406</CINEID>
<TITOL>Canvi de reines</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Cinemes Texas</CINENOM>
<LOCALITAT>Barcelona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<CICLEID>1</CICLEID>
<ver>VOSC</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33262</IDFILM>
<ses_id>1</ses_id>
<CINEID>37164</CINEID>
<TITOL>Operació Panda</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Cines Bages Centre de Manresa</CINENOM>
<LOCALITAT>Manresa</LOCALITAT>
<COMARCA>Bages</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33366</IDFILM>
<ses_id>1</ses_id>
<CINEID>37406</CINEID>
<TITOL>Amazing Grace</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Cinemes Texas</CINENOM>
<LOCALITAT>Barcelona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<CICLEID>1</CICLEID>
<ver>VOSC</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>32542</IDFILM>
<ses_id>1</ses_id>
<CINEID>37406</CINEID>
<TITOL>Els dies que vindran</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Cinemes Texas</CINENOM>
<LOCALITAT>Barcelona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<CICLEID>1</CICLEID>
<ver>VO</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33325</IDFILM>
<ses_id>1</ses_id>
<CINEID>37187</CINEID>
<TITOL>Zibila i el poder de les ratlles</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>CineBaix de Sant Feliu de Llobregat</CINENOM>
<LOCALITAT>Sant Feliu de Llobregat</LOCALITAT>
<COMARCA>Baix Llobregat</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33384</IDFILM>
<ses_id>1</ses_id>
<CINEID>37406</CINEID>
<TITOL>Curiosa</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Cinemes Texas</CINENOM>
<LOCALITAT>Barcelona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<CICLEID>1</CICLEID>
<ver>VOSC</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33283</IDFILM>
<ses_id>1</ses_id>
<CINEID>37219</CINEID>
<TITOL>Volant junts</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Cinemes Illa Carlemany de Les Escaldes</CINENOM>
<LOCALITAT>Escaldes-Engordany</LOCALITAT>
<COMARCA>Escaldes-Engordany</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33364</IDFILM>
<ses_id>1</ses_id>
<CINEID>37740</CINEID>
<TITOL>La batalla de la memòria</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Cinéma René Vautier d'Elna</CINENOM>
<LOCALITAT>Elna</LOCALITAT>
<COMARCA>Occitània</COMARCA>
<CICLEID>57257</CICLEID>
<ver>VO</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>32605</IDFILM>
<ses_id>1</ses_id>
<CINEID>37307</CINEID>
<TITOL>Chris el suís</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Sala El Mirador de Castellar del Vallès</CINENOM>
<LOCALITAT>Castellar del Vallès</LOCALITAT>
<COMARCA>Vallès Occidental</COMARCA>
<CICLEID>57142</CICLEID>
<ver>VOSC</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>32605</IDFILM>
<ses_id>1</ses_id>
<CINEID>37521</CINEID>
<TITOL>Chris el suís</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Biblioteca Singuerlin - Salvador Cabré de Santa Coloma de Gramenet</CINENOM>
<LOCALITAT>Santa Coloma de Gramenet</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<CICLEID>57142</CICLEID>
<ver>VOSC</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33329</IDFILM>
<ses_id>1</ses_id>
<CINEID>37347</CINEID>
<TITOL>Sameblod (Sami Blood)</TITOL>
<ses_data>21/02/2020</ses_data>
<CINENOM>Cineclub Altafulla Link - Sala Teresa Manero</CINENOM>
<LOCALITAT>Altafulla</LOCALITAT>
<COMARCA>Tarragonès</COMARCA>
<CICLEID>57261</CICLEID>
<ver>VOSC</ver>
<preu>0</preu>
<ORDRESESSIO>20200221</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33325</IDFILM>
<ses_id>1</ses_id>
<CINEID>37274</CINEID>
<TITOL>Zibila i el poder de les ratlles</TITOL>
<ses_data>22/02/2020</ses_data>
<CINENOM>Zumzeig Cinecooperativa</CINENOM>
<LOCALITAT>Barcelona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200222</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33262</IDFILM>
<ses_id>1</ses_id>
<CINEID>37162</CINEID>
<TITOL>Operació Panda</TITOL>
<ses_data>22/02/2020</ses_data>
<CINENOM>JCA Cinemes Lleida - Alpicat</CINENOM>
<LOCALITAT>Alpicat</LOCALITAT>
<COMARCA>Segrià</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200222</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33283</IDFILM>
<ses_id>1</ses_id>
<CINEID>37178</CINEID>
<TITOL>Volant junts</TITOL>
<ses_data>22/02/2020</ses_data>
<CINENOM>Multicines Sucre de Vic</CINENOM>
<LOCALITAT>Vic</LOCALITAT>
<COMARCA>Osona</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200222</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33325</IDFILM>
<ses_id>1</ses_id>
<CINEID>37162</CINEID>
<TITOL>Zibila i el poder de les ratlles</TITOL>
<ses_data>22/02/2020</ses_data>
<CINENOM>JCA Cinemes Lleida - Alpicat</CINENOM>
<LOCALITAT>Alpicat</LOCALITAT>
<COMARCA>Segrià</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200222</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33262</IDFILM>
<ses_id>1</ses_id>
<CINEID>37160</CINEID>
<TITOL>Operació Panda</TITOL>
<ses_data>22/02/2020</ses_data>
<CINENOM>Ocine Girona</CINENOM>
<LOCALITAT>Girona</LOCALITAT>
<COMARCA>Gironès</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200222</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33283</IDFILM>
<ses_id>1</ses_id>
<CINEID>37219</CINEID>
<TITOL>Volant junts</TITOL>
<ses_data>22/02/2020</ses_data>
<CINENOM>Cinemes Illa Carlemany de Les Escaldes</CINENOM>
<LOCALITAT>Escaldes-Engordany</LOCALITAT>
<COMARCA>Escaldes-Engordany</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200222</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33262</IDFILM>
<ses_id>1</ses_id>
<CINEID>37203</CINEID>
<TITOL>Operació Panda</TITOL>
<ses_data>22/02/2020</ses_data>
<CINENOM>Palau Balaña Multicines</CINENOM>
<LOCALITAT>Barcelona</LOCALITAT>
<COMARCA>Barcelonès</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200222</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33262</IDFILM>
<ses_id>1</ses_id>
<CINEID>37164</CINEID>
<TITOL>Operació Panda</TITOL>
<ses_data>22/02/2020</ses_data>
<CINENOM>Cines Bages Centre de Manresa</CINENOM>
<LOCALITAT>Manresa</LOCALITAT>
<COMARCA>Bages</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200222</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33325</IDFILM>
<ses_id>1</ses_id>
<CINEID>37177</CINEID>
<TITOL>Zibila i el poder de les ratlles</TITOL>
<ses_data>22/02/2020</ses_data>
<CINENOM>JCA Cinemes Tarragona - Valls</CINENOM>
<LOCALITAT>Valls</LOCALITAT>
<COMARCA>Alt Camp</COMARCA>
<CICLEID>1</CICLEID>
<ver>VD</ver>
<preu>0</preu>
<ORDRESESSIO>20200222</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33219</IDFILM>
<ses_id>1</ses_id>
<CINEID>37193</CINEID>
<TITOL>La innocència</TITOL>
<ses_data>22/02/2020</ses_data>
<CINENOM>Cinema Casal d'Agramunt</CINENOM>
<LOCALITAT>Agramunt</LOCALITAT>
<COMARCA>Urgell</COMARCA>
<CICLEID>1</CICLEID>
<ver>VO</ver>
<preu>0</preu>
<ORDRESESSIO>20200222</ORDRESESSIO>
</SESSIONS>
<SESSIONS>
<IDFILM>33197</IDFILM>
<ses_id>1</ses_id>
<CINEID>37406</CINEID>
<TITOL>Quackers: La llegenda dels ànecs</TITOL>
<ses_data>22/02/2020</ses_data>
<CINENOM>Cinemes Texas</CINENOM>
<LOCALITAT>Barcelona</LOCALITAT>
