=== AdrianGarciaB/ExerciciJavaFX/src/main/resources/xml/provacin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="dataroot" type="datarootType"/>
  <xs:complexType name="FILMType">
    <xs:sequence>
      <xs:element type="xs:string" name="IDFILM"/>
      <xs:element type="xs:string" name="PRIORITAT"/>
      <xs:element type="xs:string" name="TITOL"/>
      <xs:element type="xs:string" name="SITUACIO"/>
      <xs:element type="xs:string" name="ANY"/>
      <xs:element type="xs:string" name="CARTELL"/>
      <xs:element type="xs:string" name="ORIGINAL"/>
      <xs:element type="xs:string" name="DIRECCIO"/>
      <xs:element type="xs:string" name="INTERPRETS"/>
      <xs:element type="xs:string" name="SINOPSI"/>
      <xs:element name="VERSIO">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Doblada"/>
            <xs:enumeration value="VO"/>
            <xs:enumeration value="VOSC"/>
            <xs:enumeration value="Doblada i VOSC"/>
            <xs:enumeration value="Doblada i subtitulada en català"/>
            <xs:enumeration value="Muda amb intertítols en català"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="IDIOMA_x0020_ORIGINAL"/>
      <xs:element type="xs:string" name="QUALIFICACIO"/>
      <xs:element type="xs:string" name="TRAILER"/>
      <xs:element type="xs:string" name="WEB"/>
      <xs:element type="xs:string" name="ESTRENA"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="datarootType">
    <xs:sequence>
      <xs:element type="FILMType" name="FILM" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="generated"/>
  </xs:complexType>
</xs:schema>

=== AdrianGarciaB/ExerciciJavaFX/src/main/resources/xml/provacin.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="provacin.xsd" generated="2020-02-21T17:45:22">
<FILM>
<IDFILM>33309</IDFILM>
<PRIORITAT>100</PRIORITAT>
<TITOL>La Lur i l'Amets</TITOL>
<SITUACIO>--</SITUACIO>
<ANY>2020</ANY>
<CARTELL>lalurilamets.jpg</CARTELL>
<ORIGINAL>Lur eta Amets</ORIGINAL>
<DIRECCIO>Joseba Ponce i Imanol Zinkunegi</DIRECCIO>
<INTERPRETS>--</INTERPRETS>
<SINOPSI>Aquesta és la història de la Lur i de l’Amets. Faran un viatge inoblidable, es traslladaran a diferents èpoques i allà viuran grans aventures! Vols que els acompanyem i ens endinsem en la cultura basca?</SINOPSI>
<VERSIO>Doblada</VERSIO>
<IDIOMA_x0020_ORIGINAL>basc</IDIOMA_x0020_ORIGINAL>
<QUALIFICACIO>Apta per a tots els públics</QUALIFICACIO>
<TRAILER>5i7RTTSgRRM</TRAILER>
<WEB>--</WEB>
<ESTRENA>07/02/2020</ESTRENA>
</FILM>
<FILM>
<IDFILM>33325</IDFILM>
<PRIORITAT>99</PRIORITAT>
<TITOL>Zibila i el poder de les ratlles</TITOL>
<SITUACIO>--</SITUACIO>
<ANY>2019</ANY>
<CARTELL>zibilaielpoderdelesratlles.jpg</CARTELL>
<ORIGINAL>Zibilla ou la vie zébrée</ORIGINAL>
<DIRECCIO>Isabelle Favez, Benoît Chieux, Marina Svojíková, Marc Riba i Anna Solanas</DIRECCIO>
<INTERPRETS>--</INTERPRETS>
<SINOPSI>La Zibila és una petita zebra adoptada per una família de cavalls. El primer dia d’escola, els seus companys se’n riuen, perquè és diferent. Serà capaç, la Zibila, de recuperar la confiança en si mateixa i de guanyar el respecte dels seus companys?</SINOPSI>
<VERSIO>Doblada</VERSIO>
<IDIOMA_x0020_ORIGINAL>francès i castellà</IDIOMA_x0020_ORIGINAL>
<QUALIFICACIO>A partir de 3 anys</QUALIFICACIO>
<TRAILER>e3NXnbrJ6Yk</TRAILER>
<WEB>--</WEB>
<ESTRENA>07/02/2020</ESTRENA>
</FILM>
<FILM>
<IDFILM>33262</IDFILM>
<PRIORITAT>98</PRIORITAT>
<TITOL>Operació Panda</TITOL>
<SITUACIO>--</SITUACIO>
<ANY>2019</ANY>
<CARTELL>operaciopanda.jpg</CARTELL>
<ORIGINAL>The Big Trip</ORIGINAL>
<DIRECCIO>Natalia Nilova</DIRECCIO>
<INTERPRETS>--</INTERPRETS>
<SINOPSI>Una cigonya lliura, per error, un nadó panda a l’adreça equivocada. Serà llavors que Mic-Mic, l’os i els seus amics s’embarcaran en una gran aventura per ajudar-lo a trobar la seva família i la seva veritable llar!</SINOPSI>
<VERSIO>Doblada</VERSIO>
<IDIOMA_x0020_ORIGINAL>anglès</IDIOMA_x0020_ORIGINAL>
<QUALIFICACIO>Apta per a tots els públics</QUALIFICACIO>
<TRAILER>tUCHqAJ-obY</TRAILER>
<WEB>--</WEB>
<ESTRENA>31/01/2020</ESTRENA>
</FILM>
<FILM>
<IDFILM>33364</IDFILM>
<PRIORITAT>95</PRIORITAT>
<TITOL>La batalla de la memòria</TITOL>
<SITUACIO>--</SITUACIO>
<ANY>2009</ANY>
<CARTELL>labatalladelamemoria.jpg</CARTELL>
<ORIGINAL>La batalla de la memòria</ORIGINAL>
<DIRECCIO>Mario Pons Múria</DIRECCIO>
<INTERPRETS>--</INTERPRETS>
<SINOPSI>No és només la història d’una batalla, aquesta és la història tant dels que estigueren al front de l’Ebre, com dels homes i dones que patiren la devastació de la guerra des de la rereguarda, però sobretot és la història dels silencis que vingueren després de la Guerra Civil.</SINOPSI>
<VERSIO>VO</VERSIO>
<IDIOMA_x0020_ORIGINAL>català i castellà</IDIOMA_x0020_ORIGINAL>
<QUALIFICACIO>--</QUALIFICACIO>
<TRAILER>sjrW0m45Jbs</TRAILER>
<WEB>--</WEB>
<ESTRENA>09/11/2009</ESTRENA>
</FILM>
<FILM>
<IDFILM>33384</IDFILM>
<PRIORITAT>94</PRIORITAT>
<TITOL>Curiosa</TITOL>
<SITUACIO>--</SITUACIO>
<ANY>2019</ANY>
<CARTELL>curiosa.jpg</CARTELL>
<ORIGINAL>Curiosa</ORIGINAL>
<DIRECCIO>Lou Jeunet</DIRECCIO>
<INTERPRETS>Noémie Merlant,  Niels Schneider,  Benjamin Lavernhe,  Camélia Jordana, Amira Casar,  Scali Delpeyrat,  Emilien Diard-Detoeuf,  Mathilde Warnier, Mélodie Richard,  Damien Bonnard,  Guilhem Fabre,  Alexia Giordano</INTERPRETS>
<SINOPSI>Narra la història de Marie de Régnier, una dona lliure i independent que va experimentar amb la seva sexualitat al seu torn que va collir una prolífica carrera en el món de la literatura i la poesia. Coetània de la també escriptora Colette, Marie de Régnier es va convertir en una de les autores més influents de la França de principis de segle. Per a pagar els deutes del seu pare, Marie d'Heredia es casa amb el poeta Henri de Regnier, però ella és l'amant de Pierre Lou, un poeta que també és un erotòman i un gran viatger. És amb ell amb el qual viurà una iniciació a l'amor i l'erotisme a través del vincle fotogràfic i literari que inventen junts.</SINOPSI>
<VERSIO>VOSC</VERSIO>
<IDIOMA_x0020_ORIGINAL>francès</IDIOMA_x0020_ORIGINAL>
<QUALIFICACIO>A partir de 16 anys</QUALIFICACIO>
<TRAILER>--</TRAILER>
<WEB>--</WEB>
<ESTRENA>13/12/2019</ESTRENA>
</FILM>
<FILM>
<IDFILM>33041</IDFILM>
<PRIORITAT>93</PRIORITAT>
<TITOL>Espies disfressats</TITOL>
<SITUACIO>--</SITUACIO>
<ANY>2019</ANY>
<CARTELL>espiesdisfressats.jpg</CARTELL>
<ORIGINAL>Spies in Disguise</ORIGINAL>
<DIRECCIO>Troy Quane i Nick Bruno</DIRECCIO>
<INTERPRETS>--</INTERPRETS>
<SINOPSI>L’espia Lance Sterling i el científic Walter Beckett són pols del tot oposats. En Lance és tranquil i afable. En Walter, no. Un dia, la història gira de manera inesperada i, per aquest motiu, es veuran obligats a fer-se confiança d’una manera completament nova. I si aquesta parella tan estranya no és capaç de treballar en equip?</SINOPSI>
<VERSIO>Doblada</VERSIO>
<IDIOMA_x0020_ORIGINAL>anglès</IDIOMA_x0020_ORIGINAL>
<QUALIFICACIO>A partir de 7 anys</QUALIFICACIO>
<TRAILER>joHydaro2ho</TRAILER>
<WEB>--</WEB>
<ESTRENA>25/12/2019</ESTRENA>
</FILM>
<FILM>
<IDFILM>32605</IDFILM>
<PRIORITAT>92</PRIORITAT>
<TITOL>Chris el suís</TITOL>
<SITUACIO>--</SITUACIO>
<ANY>2018</ANY>
<CARTELL>chriselsuis.jpg</CARTELL>
<ORIGINAL>Chris the Swiss</ORIGINAL>
<DIRECCIO>Anja Kofmel</DIRECCIO>
<INTERPRETS>--</INTERPRETS>
<SINOPSI>Quan la guerra de Iugoslàvia va esclatar, joves de tot Europa hi van anar a lluitar, entre ells, un periodista suís anomenat Christian Wütenberg. Van trobar el seu cos sense vida prop de Vukovar (Croàcia), uniformat com un mercenari. L’autòpsia practicada revelava que va morir estrangulat. De fet, unes setmanes abans, en Chris s’havia convertit en membre del PIV (Primer Batalló de Voluntaris Internacionals), un grup paramilitar fundat per Eduardo Rózsa-Flores, “Chico”, que s’encarregava de “netejar” la població sèrbia en les àrees frontereres.</SINOPSI>
<VERSIO>VOSC</VERSIO>
<IDIOMA_x0020_ORIGINAL>anglès, alemany i suís</IDIOMA_x0020_ORIGINAL>
<QUALIFICACIO>A partir de 16 anys</QUALIFICACIO>
<TRAILER>vhv3O-koL9k</TRAILER>
<WEB>--</WEB>
<ESTRENA>06/02/2020</ESTRENA>
</FILM>
<FILM>
<IDFILM>33383</IDFILM>
<PRIORITAT>91</PRIORITAT>
<TITOL>Diari de bosc</TITOL>
<SITUACIO>--</SITUACIO>
<ANY>2020</ANY>
<CARTELL>diaridebosc.jpg</CARTELL>
<ORIGINAL>Diari de bosc</ORIGINAL>
<DIRECCIO>Joan Vall Karsunke</DIRECCIO>
<INTERPRETS>Xicu Cabanyes, Vicenç Altaió, Joan Vall Karsunke</INTERPRETS>
<SINOPSI>A “Diari de bosc”, el director s’apropa a la particularíssima manera de veure l’art i la vida de Xicu Cabanyes que ha convertit el Bosc de Can Ginebreda, de Porqueres (Girona), en un espai ple de figures escultòriques de grans i impressionants dimensions. Sobretot, es tracta d’escultures eròtiques, en les quals es contempla l’erotisme des de tots els punts de vista i des de la llibertat absoluta del creador i de l’espectador que les observa i s’hi pot sentir fascinat, identificat i visibilitzat.</SINOPSI>
<VERSIO>VO</VERSIO>
<IDIOMA_x0020_ORIGINAL>català</IDIOMA_x0020_ORIGINAL>
<QUALIFICACIO>--</QUALIFICACIO>
<TRAILER>vMfE7ceJF4U</TRAILER>
<WEB>--</WEB>
<ESTRENA>15/09/2019</ESTRENA>
</FILM>
<FILM>
<IDFILM>32542</IDFILM>
<PRIORITAT>91</PRIORITAT>
<TITOL>Els dies que vindran</TITOL>
<SITUACIO>--</SITUACIO>
<ANY>2019</ANY>
<CARTELL>elsdiesquevindran.jpg</CARTELL>
<ORIGINAL>Els dies que vindran (The Days to Come)</ORIGINAL>
<DIRECCIO>Carlos Marques-Marcet</DIRECCIO>
<INTERPRETS>David Verdaguer,  Maria Rodríguez Soto,  Albert Prat,  Sergi Torrecilla</INTERPRETS>
<SINOPSI>Vir i Lluís, una parella de trenta anys, aviat tindran un fill. Aquest bonic succés ocorre només un any després que la parella comenci a estar junta. Com afrontaran aquest nou repte?</SINOPSI>
<VERSIO>VO</VERSIO>
<IDIOMA_x0020_ORIGINAL>català i castellà</IDIOMA_x0020_ORIGINAL>
<QUALIFICACIO>A partir de 12 anys</QUALIFICACIO>
<TRAILER>CZZ6ijmXtqM</TRAILER>
<WEB>--</WEB>
<ESTRENA>28/06/2019</ESTRENA>
</FILM>
<FILM>
<IDFILM>33219</IDFILM>
<PRIORITAT>90</PRIORITAT>
<TITOL>La innocència</TITOL>
<SITUACIO>--</SITUACIO>
<ANY>2019</ANY>
<CARTELL>lainnocencia.jpg</CARTELL>
<ORIGINAL>La innocència (The Innocence)</ORIGINAL>
<DIRECCIO>Lucía Alemany</DIRECCIO>
<INTERPRETS>Carmen Arrufat,  Laia Marull,  Sergi López,  Joel Bosqued,  Sonia Almarcha</INTERPRETS>
<SINOPSI>Lis viu amb la seva família a un petit poble de Castelló. És una adolescent que somia amb convertir-se en artista de circ i sortir del seu poble, tot i que per aconseguir-ho haurà d’enfrontar-se amb els seus pares. És estiu, i es passa el dia al carrer amb les amigues, i flirtejant amb el seu xicot, uns anys més gran que ella. La manca d’intimitat i el xafardeig constant obliguen a Lis a dur la relació en secret per a que no arribi als seus pares. Una relació que canviarà la seva posició al món.</SINOPSI>
<VERSIO>VO</VERSIO>
<IDIOMA_x0020_ORIGINAL>català, castellà i anglès</IDIOMA_x0020_ORIGINAL>
<QUALIFICACIO>A partir de 16 anys</QUALIFICACIO>
<TRAILER>tVAfu3NDazo</TRAILER>
<WEB>--</WEB>
<ESTRENA>10/01/2020</ESTRENA>
</FILM>
<FILM>
<IDFILM>33372</IDFILM>
<PRIORITAT>90</PRIORITAT>
<TITOL>Les bones intencions</TITOL>
<SITUACIO>--</SITUACIO>
<ANY>2018</ANY>
<CARTELL>lesbonnesintentions.jpg</CARTELL>
<ORIGINAL>Les Bonnes intentions (Best Intentions)</ORIGINAL>
<DIRECCIO>Gilles Legrand</DIRECCIO>
